apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentinel-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sentinel-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sentinel-binding
subjects:
- kind: ServiceAccount
  name: sentinel-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: sentinel-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-sentinel
  template:
    metadata:
      labels:
        app: db-sentinel
    spec:
      serviceAccountName: sentinel-sa
      containers:
      - name: sentinels
        image: db-sentinel:v1
        imagePullPolicy: Never  # <--- CRITICAL for kind